site_name: The Green Book 
site_description: My personal digital resource
site_author: Jagadeesh katla
site_url: https://jagadeesh32.github.io/
nav:
  - Introduction: index.md
  - Python:
    - Basics: python/basics.md
    - Data Types: python/data-types.md
    - Loops and Conditions: python/loops-conditions.md
    - Functions: python/functions.md
    - Classes: python/classes.md
    - Oop Methodology: python/oop.md
    - Decorators: python/decorators.md
    - Connect Databases: python/databases.md
    - Use Cases: python/use-cases.md
    - Call C Functions: python/call-c-functions.md
    - Call Cpp Modules: python/call-cpp-modules.md
    - Call Rust Modules: python/call-rust-modules.md
  - Project Architecture:
    - Introduction: project-architecture/basics.md
    - Domain Driven Design: project-architecture/ddd.md
    - Project Layers: project-architecture/layers.md
    - Folder Structure: project-architecture/folder-structure.md
  - Flask:
    - Basics: flask/basics.md
    - Requests and Responses: flask/requests-response.md
    - Routers and Blueprints: flask/routes-blueprints.md
    - ORM with Sqlalchemy: flask/orm-sqlalchemy.md
  - Project Management:
    - Introduction: project-management/basics.md
    - Project Problem: project-management/problem.md
    - Outcome Solution: project-management/solution.md
    - Requirements: project-management/requirements.md
    - Project Roles: project-management/roles.md
    - Project Design: project-management/design.md
    - Cost Estimates: project-management/cost.md
    - Project Plan: project-management/planning.md
    - Project Scope: project-management/scope.md
    - Assign Tasks: project-management/tasks.md
    - Team Management: project-management/team.md
    - Project Review: project-management/review.md
    - Project Reports: project-management/reports.md
  - Cloud Computing:
    - Basics: cloud-computing/basics.md
  - Contact: contact.md
theme:
  name: material
  font:
    code: Roboto Mono
  features:
    - header.autohide
    - navigation.tracking
    - navigation.tabs.sticky
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    # - toc.integrate # here you need left table of contexts or not 
  language: en
  direction: ltr
  logo: assets/book-logo.png
  favicon: images/book-logo.png
  icon:
    repo: fontawesome/brands/github
  plugins:
    - search:
      lang: en
      separator: '[\s\-\.]+'
      prebuild_index: true
    - tags
    #- git-revision-date
    #- git-revision-date-localized:
    #  type: date
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: red

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: teal
      accent: yellow
  markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - toc:
      permalink: ⚓︎
      # toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
extra:
  #social:
  #  - icon: fontawesome/brands/twitter
  #    link: https://twitter.com/jagadeesh_katla
  #    name: Jagadeesh katla on Twitter
  generator: false
  # disqus: jagadeeshkatla-1
# copyright: Copyright &copy; 2016 - 2020 Martin Donath
#repo_url: https://github.com/jagadeesh32/green-book-docs
repo_name: jagadeesh32/green-book
